### ISSUE TITLE
Google Colab for code running

### ISSUE THREAD

**Issue by tlatkowski** [tlatkowski/gans-2.0#6]

**Comment by S1mmy** [comment]
If i run the notebook in colab, i get the following error:

`Traceback (most recent call last):
  File "run.py", line 49, in <module>
    main()
  File "run.py", line 45, in main
    run_experiment(args)
  File "run.py", line 20, in run_experiment
    gan_model = model_factories.gan_model_factory(problem_params, gan_type, input_args)
  File "/content/gans-2.0/gans/models/model_factories.py", line 39, in gan_model_factory
    generator = generator_model_factory(input_params, input_args.problem_type)
  File "/content/gans-2.0/gans/models/model_factories.py", line 153, in generator_model_factory
    return conditional_latent_to_image.LatentToImageConditionalGenerator(input_params)
  File "/content/gans-2.0/gans/models/generators/latent_to_image/conditional_latent_to_image.py", line 15, in __init__
    super().__init__(model_parameters)
  File "/content/gans-2.0/gans/models/model.py", line 15, in __init__
    self._model = self.define_model()
  File "/content/gans-2.0/gans/models/generators/latent_to_image/conditional_latent_to_image.py", line 18, in define_model
    z = Input(shape=[self.model_parameters.latent_size])
AttributeError: 'EasyDict' object has no attribute 'latent_size'`

Dont know exactly how to fix this.
